-- Belongix billing: Razorpay subscriptions + entitlements
create table if not exists public.billing_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'free' check (plan_code in ('free','plus','pro')),
  status text not null default 'inactive',
  resumes_limit integer not null default 1,
  resumes_used integer not null default 0,
  razorpay_subscription_id text unique,
  razorpay_customer_id text,
  razorpay_plan_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_payment_id text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  event_id text unique,
  event_type text not null,
  razorpay_subscription_id text,
  razorpay_payment_id text,
  user_id uuid references auth.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.billing_subscriptions enable row level security;
alter table public.billing_events enable row level security;

drop policy if exists "billing_subscriptions_select_own" on public.billing_subscriptions;
create policy "billing_subscriptions_select_own" on public.billing_subscriptions
  for select using (auth.uid() = user_id);

-- No client insert/update/delete policies: billing state is server/webhook controlled.

create index if not exists billing_events_subscription_idx
  on public.billing_events(razorpay_subscription_id);
create index if not exists billing_events_user_idx
  on public.billing_events(user_id);

create or replace function public.ensure_free_billing_row(p_user_id uuid)
returns public.billing_subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare r public.billing_subscriptions;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then raise exception 'UNAUTHORIZED'; end if;
  insert into public.billing_subscriptions(user_id, plan_code, status, resumes_limit)
  values (p_user_id, 'free', 'active', 1)
  on conflict (user_id) do nothing;
  select * into r from public.billing_subscriptions where user_id = p_user_id;
  return r;
end;
$$;

revoke all on function public.ensure_free_billing_row(uuid) from public;
grant execute on function public.ensure_free_billing_row(uuid) to authenticated;

create or replace function public.touch_billing_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists billing_subscriptions_updated_at on public.billing_subscriptions;
create trigger billing_subscriptions_updated_at
before update on public.billing_subscriptions
for each row execute function public.touch_billing_updated_at();

-- NOTE: Run resume-schema.sql before using the quota RPCs below.
