-- Belongix production schema bundle.
-- Run this file once in Supabase SQL Editor.
-- It is idempotent for the included tables/functions/policies.

-- Safe profile migration for the resume-only Belongix product.
create table if not exists public.career_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  target_role text,
  email text,
  phone text,
  city text,
  linkedin_url text,
  summary text,
  skills jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.career_profiles enable row level security;
drop policy if exists "career_profiles_select_own" on public.career_profiles;
create policy "career_profiles_select_own" on public.career_profiles for select using (auth.uid() = user_id);
drop policy if exists "career_profiles_insert_own" on public.career_profiles;
create policy "career_profiles_insert_own" on public.career_profiles for insert with check (auth.uid() = user_id);
drop policy if exists "career_profiles_update_own" on public.career_profiles;
create policy "career_profiles_update_own" on public.career_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "career_profiles_delete_own" on public.career_profiles;
create policy "career_profiles_delete_own" on public.career_profiles for delete using (auth.uid() = user_id);

-- Belongix billing: Razorpay subscriptions + entitlements
create table if not exists public.billing_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_code text not null default 'free' check (plan_code in ('free','plus','pro')),
  status text not null default 'inactive',
  resumes_limit integer not null default 1,
  resumes_used integer not null default 0,
  razorpay_subscription_id text unique,
  razorpay_customer_id text,
  razorpay_plan_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_payment_id text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  event_id text unique,
  event_type text not null,
  razorpay_subscription_id text,
  razorpay_payment_id text,
  user_id uuid references auth.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.billing_subscriptions enable row level security;
alter table public.billing_events enable row level security;

drop policy if exists "billing_subscriptions_select_own" on public.billing_subscriptions;
create policy "billing_subscriptions_select_own" on public.billing_subscriptions
  for select using (auth.uid() = user_id);

-- No client insert/update/delete policies: billing state is server/webhook controlled.

create index if not exists billing_events_subscription_idx
  on public.billing_events(razorpay_subscription_id);
create index if not exists billing_events_user_idx
  on public.billing_events(user_id);

create or replace function public.ensure_free_billing_row(p_user_id uuid)
returns public.billing_subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare r public.billing_subscriptions;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then raise exception 'UNAUTHORIZED'; end if;
  insert into public.billing_subscriptions(user_id, plan_code, status, resumes_limit)
  values (p_user_id, 'free', 'active', 1)
  on conflict (user_id) do nothing;
  select * into r from public.billing_subscriptions where user_id = p_user_id;
  return r;
end;
$$;

revoke all on function public.ensure_free_billing_row(uuid) from public;
grant execute on function public.ensure_free_billing_row(uuid) to authenticated;

create or replace function public.touch_billing_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists billing_subscriptions_updated_at on public.billing_subscriptions;
create trigger billing_subscriptions_updated_at
before update on public.billing_subscriptions
for each row execute function public.touch_billing_updated_at();

-- NOTE: Run resume-schema.sql before using the quota RPCs below.

-- Belongix resume storage + secure creation path
create table if not exists public.resumes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled Resume',
  content jsonb not null default '{}'::jsonb,
  target_job text,
  career_level text,
  template text not null default 'classic',
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.resumes
  add column if not exists title text not null default 'Untitled Resume',
  add column if not exists content jsonb not null default '{}'::jsonb,
  add column if not exists target_job text,
  add column if not exists career_level text,
  add column if not exists template text not null default 'classic',
  add column if not exists is_deleted boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.resumes enable row level security;

-- Remove any legacy INSERT/ALL policy so quota enforcement cannot be bypassed.
do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname='public' and tablename='resumes' and cmd in ('INSERT','ALL')
  loop
    execute format('drop policy if exists %I on public.resumes', p.policyname);
  end loop;
end $$;

drop policy if exists "resumes_select_own" on public.resumes;
create policy "resumes_select_own" on public.resumes for select using (auth.uid() = user_id);

drop policy if exists "resumes_insert_own" on public.resumes;
-- Intentionally no direct INSERT policy. New resumes must be created through
-- create_resume_with_quota(), which atomically enforces the billing entitlement.

drop policy if exists "resumes_update_own" on public.resumes;
create policy "resumes_update_own" on public.resumes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "resumes_delete_own" on public.resumes;
create policy "resumes_delete_own" on public.resumes for delete using (auth.uid() = user_id);

create index if not exists resumes_user_updated_idx on public.resumes(user_id, updated_at desc);

create or replace function public.touch_resumes_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists resumes_updated_at on public.resumes;
create trigger resumes_updated_at
before update on public.resumes
for each row execute function public.touch_resumes_updated_at();

create or replace function public.create_resume_with_quota(
  p_title text,
  p_content jsonb,
  p_target_job text default null,
  p_career_level text default null,
  p_template text default 'classic'
)
returns public.resumes
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  b public.billing_subscriptions;
  r public.resumes;
  is_paid boolean;
begin
  if uid is null then raise exception 'UNAUTHORIZED'; end if;

  insert into public.billing_subscriptions(user_id, plan_code, status, resumes_limit)
  values (uid, 'free', 'active', 1)
  on conflict (user_id) do nothing;

  select * into b from public.billing_subscriptions where user_id = uid for update;
  is_paid := b.plan_code in ('plus','pro');

  if is_paid then
    if b.status not in ('authenticated','active') then
      raise exception 'SUBSCRIPTION_INACTIVE';
    end if;
    if b.current_period_end is not null and b.current_period_end <= now() then
      raise exception 'SUBSCRIPTION_PERIOD_EXPIRED';
    end if;
  end if;

  if b.resumes_used >= b.resumes_limit then
    raise exception 'RESUME_LIMIT_REACHED';
  end if;

  insert into public.resumes(user_id,title,content,target_job,career_level,template)
  values (
    uid,
    coalesce(nullif(trim(p_title),''),'Untitled Resume'),
    coalesce(p_content,'{}'::jsonb),
    nullif(trim(p_target_job),''),
    nullif(trim(p_career_level),''),
    coalesce(nullif(trim(p_template),''),'classic')
  ) returning * into r;

  update public.billing_subscriptions
  set resumes_used = resumes_used + 1
  where user_id = uid;

  return r;
end;
$$;

revoke all on function public.create_resume_with_quota(text,jsonb,text,text,text) from public;
grant execute on function public.create_resume_with_quota(text,jsonb,text,text,text) to authenticated;

create or replace function public.get_resume_quota()
returns table(
  plan_code text,
  status text,
  resumes_limit integer,
  resumes_used integer,
  resumes_remaining integer,
  current_period_end timestamptz,
  cancel_at_period_end boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  b public.billing_subscriptions;
begin
  if uid is null then raise exception 'UNAUTHORIZED'; end if;
  insert into public.billing_subscriptions(user_id, plan_code, status, resumes_limit)
  values (uid, 'free', 'active', 1)
  on conflict (user_id) do nothing;
  select * into b from public.billing_subscriptions where user_id = uid;
  return query select b.plan_code,b.status,b.resumes_limit,b.resumes_used,
    greatest(b.resumes_limit-b.resumes_used,0),b.current_period_end,b.cancel_at_period_end;
end;
$$;

revoke all on function public.get_resume_quota() from public;
grant execute on function public.get_resume_quota() to authenticated;

-- Belongix AI usage ledger. Required by the resume-ai Edge Function.
create table if not exists public.ai_usage (
  user_id uuid primary key references auth.users(id) on delete cascade,
  usage_date date not null default current_date,
  count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.ai_usage enable row level security;

drop policy if exists "ai_usage_select_own" on public.ai_usage;
create policy "ai_usage_select_own" on public.ai_usage for select using (auth.uid() = user_id);

create or replace function public.consume_ai_usage(p_user_id uuid, p_limit integer default 50)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  c integer;
begin
  if auth.uid() is null or auth.uid() <> p_user_id then raise exception 'UNAUTHORIZED'; end if;
  insert into public.ai_usage(user_id, usage_date, count)
  values (p_user_id, current_date, 0)
  on conflict (user_id) do update
    set usage_date = excluded.usage_date,
        count = case when public.ai_usage.usage_date = excluded.usage_date then public.ai_usage.count else 0 end,
        updated_at = now();
  select count into c from public.ai_usage where user_id = p_user_id;
  if c >= greatest(p_limit,0) then return false; end if;
  update public.ai_usage set count = count + 1, updated_at = now() where user_id = p_user_id;
  return true;
end;
$$;

revoke all on function public.consume_ai_usage(uuid,integer) from public;
grant execute on function public.consume_ai_usage(uuid,integer) to authenticated;
